In [1]:
#1. Import the numpy package under the name `np`
import numpy as np

In [2]:
#2. Print the numpy version and the configuration 
print(np.__version__)

1.24.2


In [3]:
#3. Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4. How to find the memory size of any array
arr = np.zeros((3, 4))
memory_size = arr.nbytes
print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 96 bytes


In [5]:
#5. How to get the documentation of the numpy add function from the command line? 
!pydoc numpy.add

Help on ufunc in numpy:

numpy.add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the

In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1 
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7. Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#8. Reverse a vector (first element becomes last)
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


In [11]:
#11. Create a 3x3 identity matrix 
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12. Create a 3x3x3 array with random values
array = np.random.rand(3, 3, 3)
print(array)

[[[0.2600987  0.83410799 0.23398376]
  [0.55125648 0.59890766 0.51965612]
  [0.48027555 0.27118139 0.04204741]]

 [[0.4500828  0.50865605 0.0611704 ]
  [0.41381347 0.30435037 0.69220398]
  [0.88968317 0.17236591 0.35696222]]

 [[0.2869861  0.12803802 0.99130389]
  [0.12269432 0.18114666 0.2595386 ]
  [0.52413748 0.30338938 0.8865944 ]]]


In [13]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
array = np.random.rand(10, 10)
print("Array:")
print(array)

minimum_value = np.min(array)
maximum_value = np.max(array)

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)

Array:
[[0.41451315 0.54290999 0.37307455 0.53308628 0.09487199 0.67481332
  0.33443012 0.63289198 0.87093341 0.3870597 ]
 [0.06228667 0.44371697 0.97273596 0.20966109 0.16804364 0.99120028
  0.74041621 0.28317024 0.56588234 0.37001388]
 [0.90901152 0.96814478 0.17761525 0.33965337 0.15215771 0.47991601
  0.17848393 0.94535701 0.40353653 0.4493874 ]
 [0.6184716  0.44564123 0.7873942  0.65556251 0.83406042 0.42720224
  0.19488828 0.57052051 0.44490083 0.73066899]
 [0.63279932 0.50826095 0.28106473 0.99013059 0.41029828 0.93172506
  0.22212965 0.47172461 0.36692025 0.91029118]
 [0.07469321 0.09446058 0.18994322 0.85947318 0.49476201 0.99255602
  0.95275159 0.57180137 0.78280012 0.02654144]
 [0.64934706 0.27318481 0.27862846 0.2914218  0.96415527 0.27932463
  0.17767134 0.29066899 0.27777503 0.41910207]
 [0.76684034 0.61965938 0.52748414 0.05410785 0.25349588 0.67438196
  0.51439755 0.32643701 0.00874214 0.8591927 ]
 [0.55121091 0.49494893 0.83328094 0.16050212 0.14488034 0.17314592
  0.2

In [14]:
#14. Create a random vector of size 30 and find the mean value
import numpy as np

vector = np.random.rand(30)
print("Vector:")
print(vector)

mean_value = np.mean(vector)
print("Mean value:", mean_value)

Vector:
[0.99140533 0.83746733 0.74974032 0.62058356 0.23994602 0.04951422
 0.62882424 0.14367586 0.87358273 0.65794231 0.90837981 0.6877444
 0.6451069  0.44861688 0.56403324 0.91032287 0.20596561 0.32994483
 0.9193239  0.7221111  0.59529393 0.62044426 0.85953534 0.26212058
 0.37007704 0.86225528 0.6399661  0.73814587 0.38174405 0.19021849]
Mean value: 0.5884677459563024


In [15]:
#15. Create a 2d array with 1 on the border and 0 inside
rows = 5
cols = 5

array = np.zeros((rows, cols))
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#16. How to add a border (filled with 0's) around an existing array?
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

border_width = 1

padded_array = np.pad(existing_array, pad_width=border_width, mode='constant')

print("Existing Array:")
print(existing_array)

print("\nPadded Array:")
print(padded_array)

Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded Array:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [17]:
#17. What is the result of the following expression? 
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [18]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.zeros((5, 5))
diagonal_values = [1, 2, 3, 4]

# Assign values just below the diagonal
np.fill_diagonal(matrix[1:], diagonal_values)

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
matrix = np.zeros((8, 8), dtype=str)
matrix[::2, ::2] = "★"  # Set stars in even rows and even columns
matrix[1::2, 1::2] = "★"  # Set stars in odd rows and odd columns
print(matrix)

[['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']
 ['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']
 ['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']
 ['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']]


In [20]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)  # Compute the total number of elements in the array
element_index = 100

# Check if the element index is within the valid range
if element_index >= total_elements:
    print("Element index is out of range for the given array shape.")
else:
    # Compute the index (x, y, z) of the element
    indices = np.unravel_index(element_index, array_shape)
    print("Index (x, y, z) of the 100th element:", indices)

Index (x, y, z) of the 100th element: (1, 5, 4)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function

base_pattern = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(base_pattern, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#22. Normalize a 5x5 random matrix
random_matrix = np.random.random((5, 5))
normalized_matrix = np.linalg.norm(random_matrix)

print("Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Random Matrix:
[[0.91065833 0.87119061 0.33501859 0.5609323  0.85660681]
 [0.12078236 0.23657566 0.70507443 0.62242966 0.57707361]
 [0.74027321 0.01175093 0.12173513 0.73794186 0.92750857]
 [0.10396028 0.27483352 0.38547935 0.59114143 0.72530677]
 [0.33125858 0.57572338 0.44295693 0.74245023 0.23624412]]

Normalized Matrix:
2.8913212316725634


In [23]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
# Define the custom dtype
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
# Create a color array using the custom dtype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(color_array)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Product:")
print(product)

Matrix 1:
[[0.70735215 0.26115123 0.09123711]
 [0.64200547 0.95742437 0.58980734]
 [0.66260752 0.84979393 0.6316926 ]
 [0.64477446 0.30126259 0.87950851]
 [0.7587106  0.80031164 0.3164532 ]]

Matrix 2:
[[0.38638104 0.68565013]
 [0.95350493 0.40472989]
 [0.85074252 0.07230773]]

Matrix Product:
[[0.59993573 0.59728895]
 [1.66274177 0.87033703]
 [1.60370944 0.8439302 ]
 [1.28461928 0.62761494]
 [1.32547267 0.86700208]]


In [25]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.

arr = np.array([1, 5, 4, 9, 7, 2, 6, 3, 8])

# Find the indices of elements between 3 and 8
indices = np.where((arr >= 3) & (arr <= 8))

# Negate the elements at the found indices
arr[indices] = -arr[indices]

print(arr)

[ 1 -5 -4  9 -7  2 -6 -3 -8]


In [26]:
#26. What is the output of the following script? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [27]:
#27. Consider an integer vector Z, which of these expressions are legal?
"""Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z """

'Z**Z\n2 << Z >> 2\nZ <- Z\n1j*Z\nZ/1/1\nZ<Z>Z '

In [28]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_35512/1713965767.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_35512/1713965767.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_35512/1713965767.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [29]:
#29. How to round away from zero a float array ?

arr = np.array([-1.5, 2.3, -4.7, 5.9, -0.1])

rounded_arr = np.ceil(np.abs(arr)) * np.copysign(1, arr)

print(rounded_arr)

[-2.  3. -5.  6. -1.]


In [30]:
#30. How to find common values between two arrays?

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


In [31]:
#31. How to ignore all numpy warnings (not recommended)? 

import numpy as np
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=FutureWarning)

# Reset warnings to default behavior
warnings.resetwarnings()

In [32]:
#32. Is the following expressions true? 
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_35512/652847447.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [35]:
#33. How to get the dates of yesterday, today and tomorrow?
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-19
Today: 2024-02-20
Tomorrow: 2024-02-21


In [37]:
#34. How to get all the dates corresponding to the month of July 2016? 
from datetime import datetime, timedelta

def get_dates_in_month(year, month):
    start_date = datetime(year, month, 1).date()
    next_month = start_date.replace(day=28) + timedelta(days=4)  # Add 4 days to go beyond end of month
    end_date = next_month - timedelta(days=next_month.day)

    dates_in_month = []
    current_date = start_date
    while current_date <= end_date:
        dates_in_month.append(current_date)
        current_date += timedelta(days=1)

    return dates_in_month

# Get all the dates in July 2016
dates_july_2016 = get_dates_in_month(2016, 7)

# Print the dates
for date in dates_july_2016:
    print(date)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


In [38]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)

# Print the result
print(A)

[-2.5 -3.5 -4.5]


In [39]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
# Generate a random array of positive numbers
arr = np.random.rand(5) * 10  # Adjust the size of the array as needed

# Method 1: Using np.floor()
int_part_1 = np.floor(arr)
print("Method 1 (np.floor()):", int_part_1)

# Method 2: Using np.trunc()
int_part_2 = np.trunc(arr)
print("Method 2 (np.trunc()):", int_part_2)

# Method 3: Using np.ceil() and subtraction
int_part_3 = arr - (arr % 1)
print("Method 3 (np.ceil() and subtraction):", int_part_3)

# Method 4: Using np.astype()
int_part_4 = arr.astype(int)
print("Method 4 (np.astype()):", int_part_4)

Method 1 (np.floor()): [7. 0. 8. 5. 0.]
Method 2 (np.trunc()): [7. 0. 8. 5. 0.]
Method 3 (np.ceil() and subtraction): [7. 0. 8. 5. 0.]
Method 4 (np.astype()): [7 0 8 5 0]


In [40]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 

# Create a 1-dimensional array ranging from 0 to 4
row_values = np.arange(5)

# Create a 5x5 matrix by broadcasting the row values
matrix = np.tile(row_values, (5, 1))

# Print the matrix
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [41]:
#38. Consider a generator function that generates 10 integers and use it to build an array 
def integer_generator():
    for i in range(10):
        yield i

# Create an array using the generator function
array = np.fromiter(integer_generator(), dtype=int)

# Print the array
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 
vector = np.linspace(0, 1, 10, endpoint=False)[1:]

# Print the vector
print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [43]:
#40. Create a random vector of size 10 and sort it

# Create a random vector of size 10
vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(vector)

# Print the sorted vector
print(sorted_vector)

[0.10720439 0.27329197 0.35781046 0.35957497 0.5253771  0.55873516
 0.66370676 0.78172905 0.82115779 0.87592437]


In [44]:
#41. How to sum a small array faster than np.sum?
import math
arr = [1, 2, 3, 4, 5]
total = sum(arr)


arr = [1.1, 2.2, 3.3, 4.4, 5.5]
total = math.fsum(arr)

In [45]:
#42. Consider two random array A and B, check if they are equal
# Generate two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

# Print the result
print(are_equal)

False


In [46]:
"""
#43. Make an array immutable (read-only) (★★☆)
mutable_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable
immutable_array = mutable_array.copy()
immutable_array.flags.writeable = False

# Try to modify the immutable array (raises an error)
immutable_array[0] = 10
"""

'\n#43. Make an array immutable (read-only) (★★☆)\nmutable_array = np.array([1, 2, 3, 4, 5])\n\n# Make the array immutable\nimmutable_array = mutable_array.copy()\nimmutable_array.flags.writeable = False\n\n# Try to modify the immutable array (raises an error)\nimmutable_array[0] = 10\n'

In [47]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x, y)
theta = np.arctan2(y, x)

# Stack r and theta to form a 10x2 matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

# Print the polar coordinates
print(polar_coords)

[[1.01560018 1.21692744]
 [0.5558618  0.96094967]
 [1.12441607 0.85746461]
 [0.48398954 1.03823521]
 [1.1070904  0.96039147]
 [0.95631293 0.49186018]
 [0.99398972 0.00963752]
 [0.7728305  1.47972449]
 [0.58290941 0.18894245]
 [0.93139619 0.01028384]]


In [49]:
#45. Create random vector of size 10 and replace the maximum value by 0
# Create a random vector of size 10
vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(vector)

# Replace the maximum value with 0
vector[vector == max_value] = 0

# Print the updated vector
print(vector)

[0.         0.00084097 0.42951948 0.18616711 0.79066871 0.70809965
 0.83279162 0.39442434 0.47451003 0.56673062]


In [50]:
#46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area
# Define the number of points in each dimension
num_points = 5

# Create a grid of x and y coordinates
x_coords = np.linspace(0, 1, num_points)
y_coords = np.linspace(0, 1, num_points)
xx, yy = np.meshgrid(x_coords, y_coords)

# Create a structured array
structured_array = np.zeros((num_points*num_points,), dtype=[('x', float), ('y', float)])
structured_array['x'] = xx.flatten()
structured_array['y'] = yy.flatten()

# Print the structured array
print(structured_array)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


In [51]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Compute the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

# Print the Cauchy matrix
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [52]:
#48. Print the minimum and maximum representable value for each numpy scalar type
# Integer scalar types
integer_types = [np.int8, np.int16, np.int32, np.int64,
                 np.uint8, np.uint16, np.uint32, np.uint64]

for int_type in integer_types:
    info = np.iinfo(int_type)
    print(f"{int_type.__name__}: min={info.min}, max={info.max}")

# Floating-point scalar types
float_types = [np.float16, np.float32, np.float64]

for float_type in float_types:
    info = np.finfo(float_type)
    print(f"{float_type.__name__}: min={info.min}, max={info.max}")

int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


In [53]:
#49. How to print all the values of an array?

# Create an example array
arr = np.array([1, 2, 3, 4, 5])
# Print all the values of the array
print(arr)


[1 2 3 4 5]


In [54]:
#50. How to find the closest value (to a given scalar) in a vector?
# Example vector
vector = np.array([1, 4, 7, 10])

# Target scalar
target = 6

# Find the index of the closest value
index = np.abs(vector - target).argmin()

# Get the closest value
closest_value = vector[index]

# Print the closest value
print(closest_value)

7


In [55]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)

# Define the structured data type
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                  ('color', [('r', int), ('g', int), ('b', int)])])

# Create a structured array
structured_array = np.array([((1.0, 2.0), (255, 0, 0)),
                             ((3.0, 4.0), (0, 255, 0)),
                             ((5.0, 6.0), (0, 0, 255))], dtype=dtype)

# Print the structured array
print(structured_array)

[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]


In [56]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
import numpy as np

# Generate random vector with shape (100, 2)
random_vector = np.random.rand(100, 2)

# Calculate point-by-point distances
distances = np.zeros((100, 100))  # Initialize an empty distance matrix

for i in range(100):
    for j in range(100):
        x1, y1 = random_vector[i]  # Coordinates of point i
        x2, y2 = random_vector[j]  # Coordinates of point j
        distances[i, j] = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print(distances)

[[0.         0.45546445 0.58546885 ... 0.38462211 0.29131696 0.15422216]
 [0.45546445 0.         0.53728201 ... 0.32090664 0.40396387 0.51709826]
 [0.58546885 0.53728201 0.         ... 0.24367692 0.29415745 0.73581759]
 ...
 [0.38462211 0.32090664 0.24367692 ... 0.         0.13588202 0.52270807]
 [0.29131696 0.40396387 0.29415745 ... 0.13588202 0.         0.44244637]
 [0.15422216 0.51709826 0.73581759 ... 0.52270807 0.44244637 0.        ]]


In [57]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
# Create a float array with 32-bit precision
float_array = np.array([1.5, 2.7, 3.3], dtype=np.float32)
print("Float array:", float_array)

# Convert the float array to an integer array in place
int_array = float_array.view(np.int32)
print("Integer array:", int_array)

Float array: [1.5 2.7 3.3]
Integer array: [1069547520 1076677837 1079194419]


In [58]:
""" #54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
    _summary_
    
data = []

with open(filename, 'r') as file:
    csv_reader = csv.reader(file, delimiter=',')
    for row in csv_reader:
        stripped_row = [cell.strip() for cell in row]
        data.append(stripped_row)

print(data)

"""

" #54. How to read the following file? (★★☆)\n1, 2, 3, 4, 5\n6,  ,  , 7, 8\n ,  , 9,10,11\n    _summary_\n    \ndata = []\n\nwith open(filename, 'r') as file:\n    csv_reader = csv.reader(file, delimiter=',')\n    for row in csv_reader:\n        stripped_row = [cell.strip() for cell in row]\n        data.append(stripped_row)\n\nprint(data)\n\n"

In [59]:
#55. What is the equivalent of enumerate for numpy arrays?
## The equivalent of enumerate for NumPy arrays is the np.ndenumerate function.
arr = np.array([[1, 2, 3], [4, 5, 6]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [60]:
#56. Generate a generic 2D Gaussian-like array 
from scipy.stats import multivariate_normal

# Define parameters for the Gaussian distribution
mean = [0, 0]  # Mean of the distribution
cov = [[1, 0], [0, 1]]  # Covariance matrix

# Generate a 2D grid of coordinates
x = np.linspace(-3, 3, 100)
y = np.linspace(-3, 3, 100)
X, Y = np.meshgrid(x, y)
pos = np.dstack((X, Y))

# Calculate the Gaussian distribution values at each coordinate
Z = multivariate_normal.pdf(pos, mean, cov)

In [61]:
#57. How to randomly place p elements in a 2D array?
# Define the size of the 2D array
rows = 5
cols = 5

# Define the number of elements to randomly place
p = 5

# Create an empty 2D array
arr = np.zeros((rows, cols))

# Generate random indices for placing the elements
indices = np.random.choice(rows * cols, p, replace=False)

# Set the randomly chosen indices to 1
arr.flat[indices] = 1

# Print the resulting array
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [62]:
#58. Subtract the mean of each row of a matrix
# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract the mean of each row
mean_subtracted = matrix - np.mean(matrix, axis=1, keepdims=True)

# Print the result
print(mean_subtracted)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [63]:
#59. How to sort an array by the nth column?

# Create an array
arr = np.array([[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]])

# Sort the array by the nth column (0-based indexing)
n = 1
sorted_arr = arr[arr[:, n].argsort()]

# Print the sorted array
print(sorted_arr)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [64]:
#60. How to tell if a given 2D array has null columns?

# Create a 2D array
arr = np.array([[1, 2, 3],
                [0, 0, 0],
                [4, 5, 6],
                [0, 0, 0]])

# Check if any columns are null
is_null_column = np.all(arr == 0, axis=0)

# Print the result
print(is_null_column)

[False False False]


In [65]:
#61. Find the nearest value from a given value in an array

# Create an array
arr = np.array([1, 3, 7, 9, 15])

# Given value
value = 8

# Find the nearest value
nearest_value = arr[np.abs(arr - value).argmin()]

# Print the result
print(nearest_value)


7


In [66]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

# Create the arrays
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

# Get the iterators
iter1 = np.nditer(arr1)
iter2 = np.nditer(arr2)

# Compute the sum using the iterators
sum_result = 0
for x, y in zip(iter1, iter2):
    sum_result += (x + y)

# Print the result
print(sum_result)

21


In [67]:
class NamedArray:
    def __init__(self, name, array):
        self.name = name
        self.array = array

    def __str__(self):
        return f"Name: {self.name}\nArray: {self.array}"

# Create an instance of the NamedArray class
arr = NamedArray("MyArray", [1, 2, 3, 4, 5])

# Access the name attribute
print(arr.name)  # Output: MyArray

# Access the array attribute
print(arr.array)  # Output: [1, 2, 3, 4, 5]

# Print the NamedArray instance

MyArray
[1, 2, 3, 4, 5]


In [68]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Index vector
indices = np.array([0, 1, 3, 1, 4])

# Create a copy of the vector
result = vector.copy()

# Add 1 to each element indexed by the second vector
np.add.at(result, indices, 1)

# Print the result
print(result)

[2 4 3 5 6]


In [69]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 


# Define the vector X and index list I
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 1, 2, 2])

# Calculate the size of the output array F
F_size = np.max(I) + 1

# Initialize the output array F with zeros
F = np.zeros(F_size)

# Accumulate elements of X into F based on the indices in I
np.add.at(F, I, X)

print(F)

[1. 5. 9.]


In [70]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

# Generate a random image with dimensions (w, h, 3)
w, h = 100, 100
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array with shape (w * h, 3)
reshaped_image = image.reshape(-1, 3)

# Compute the number of unique colors
unique_colors = np.unique(reshaped_image, axis=0)

# Get the number of unique colors
num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)

Number of unique colors: 9998


In [71]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
# Create a four-dimensional array
array = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Compute the sum over the last two axes
sum_last_two_axes = np.sum(array, axis=(-2, -1))

# Print the result
print(sum_last_two_axes)

[[ 86  95  83]
 [109  96 115]]


In [72]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

# Create the one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create the subset indices vector S
S = np.array([0, 0, 1, 1, 1, 2, 2, 2, 2, 2])

# Compute the means of the subsets
means = np.bincount(S, weights=D) / np.bincount(S)

# Print the result
print(means)

[1.5 4.  8. ]


In [73]:
#69. How to get the diagonal of a dot product?

# Create two matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

# Compute the dot product of A and B
dot_product = np.einsum('ij, jk -> ik', A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

# Print the result
print(diagonal)

[1 5 9]


In [74]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

# Create the original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Number of consecutive zeros to insert
zeros_count = 3

# Compute the length of the new vector
new_length = original_vector.size + (original_vector.size - 1) * zeros_count

# Create an array of zeros with the appropriate length
zeros = np.zeros(new_length, dtype=original_vector.dtype)

# Insert the original values and zeros at the correct positions
zeros[::zeros_count + 1] = original_vector

# Print the result
print(zeros)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [75]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
# Create a three-dimensional array A with dimensions (5, 5, 3)
A = np.random.random((5, 5, 3))

# Create a two-dimensional array B with dimensions (5, 5)
B = np.random.random((5, 5))

# Multiply array A by array B
result = A * B[:, :, np.newaxis]

# Print the result
print(result)

[[[4.14277717e-02 6.19516761e-02 3.99592997e-01]
  [1.77706877e-01 1.73078551e-01 6.86755139e-01]
  [2.99742480e-02 5.61322264e-02 4.28967575e-02]
  [1.32070730e-03 3.72545814e-03 2.28851694e-02]
  [7.62579409e-04 2.10868784e-02 9.46111479e-03]]

 [[2.89853194e-02 1.21303085e-01 2.14215773e-01]
  [7.96772981e-02 1.52044127e-01 2.86246900e-02]
  [4.04204191e-01 6.59958828e-02 9.11299846e-02]
  [1.37556581e-01 3.64139372e-01 1.29689983e-01]
  [4.17254600e-01 4.66091355e-01 2.10001903e-01]]

 [[4.77784042e-01 5.49269468e-01 3.74620901e-02]
  [5.52396741e-02 1.03426826e-01 1.63019013e-01]
  [2.11087796e-02 2.97152427e-03 2.12679662e-01]
  [5.12273573e-01 3.63302882e-01 3.24574708e-01]
  [7.63279846e-02 1.44661663e-01 5.48375087e-01]]

 [[2.81561050e-01 2.06594926e-01 1.38702255e-02]
  [3.30757295e-01 3.78658621e-03 8.25049668e-01]
  [5.00151161e-02 3.23396053e-01 2.22780497e-01]
  [2.97245103e-01 3.66155904e-01 1.43257426e-01]
  [2.32091858e-01 2.32236353e-01 5.69021760e-01]]

 [[4.4651163

In [76]:
#72. How to swap two rows of an array?

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 1 and 2
array[1], array[2] = array[2], array[1]

# Print the result
print(array)

[[1 2 3]
 [7 8 9]
 [7 8 9]]


In [77]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

# Set of 10 triplets describing triangles
triplets = np.array([[1, 2, 3],
                     [2, 3, 4],
                     [3, 4, 5],
                     [4, 5, 6],
                     [5, 6, 7],
                     [6, 7, 8],
                     [7, 8, 9],
                     [8, 9, 10],
                     [9, 10, 11],
                     [10, 11, 12]])

# Reshape the triplets to form line segments
line_segments = triplets.reshape(-1, 2)

# Sort each line segment to ensure consistency
line_segments.sort(axis=1)

# Find the unique line segments
unique_segments = np.unique(line_segments, axis=0)

# Print the result
print(unique_segments)

[[ 1  2]
 [ 2  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]]


In [78]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

# Sorted array C corresponding to bincount
C = np.array([0, 1, 2, 2, 3, 4, 4, 4, 5])

# Produce array A such that np.bincount(A) == C
A = np.repeat(np.arange(len(C)), C)

# Print the result
print(A)

[1 2 2 3 3 4 4 4 5 5 5 5 6 6 6 6 7 7 7 7 8 8 8 8 8]


In [80]:
#75. How to compute averages using a sliding window over an array? 
# Input array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Window size
window_size = 3

# Define the weights for the sliding window
weights = np.ones(window_size) / window_size

# Compute the averages using the sliding window
averages = np.convolve(array, weights, mode='valid')

# Print the result
print(averages)

[2. 3. 4. 5. 6. 7. 8. 9.]


In [81]:
# One-dimensional array Z
Z = np.array([1, 2, 3, 4, 5])

# Build the two-dimensional array
n = 3  # Number of elements per row
m = len(Z) - n + 1  # Number of rows
result = np.zeros((m, n), dtype=Z.dtype)

for i in range(m):
    result[i] = Z[i:i+n]

# Print the result
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [82]:
#77. How to negate a boolean, or to change the sign of a float inplace?

b = True
b = not b
print(b)  # False

f = 3.14
f *= -1
print(f)  # -3.14

False
-3.14


In [83]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

def distance_to_lines(P0, P1, p):
    # Convert points to NumPy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    p = np.array(p)

    # Compute vectors along each line segment
    v = P1 - P0

    # Compute vectors from P0 to p
    w = p - P0

    # Compute dot products
    dot_products = np.einsum('ij,ij->i', v, w)

    # Compute squared lengths of each line segment
    squared_lengths = np.einsum('ij,ij->i', v, v)

    # Compute distances from p to each line
    distances = np.abs(dot_products) / np.sqrt(squared_lengths)

    return distances

# Example usage
P0 = [(1, 1), (2, 2), (3, 3)]
P1 = [(4, 4), (5, 5), (6, 6)]
p = (2, 5)

distances = distance_to_lines(P0, P1, p)
print(distances)

[3.53553391 2.12132034 0.70710678]


In [84]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?


def distance_to_lines(P0, P1, P):
    # Convert points to NumPy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    P = np.array(P)

    # Compute vectors along each line segment
    v = P1 - P0

    # Initialize array to store distances
    distances = np.zeros((len(P), len(P0)))

    # Compute distances from each point in P to each line
    for i, p in enumerate(P):
        w = p - P0
        dot_products = np.sum(v * w, axis=1)
        squared_lengths = np.sum(v * v, axis=1)
        distances[i] = np.abs(dot_products) / np.sqrt(squared_lengths)

    return distances

# Example usage
P0 = [(1, 1), (2, 2), (3, 3)]
P1 = [(4, 4), (5, 5), (6, 6)]
P = [(2, 5), (3, 4), (4, 3)]

distances = distance_to_lines(P0, P1, P)
print(distances)

[[3.53553391 2.12132034 0.70710678]
 [3.53553391 2.12132034 0.70710678]
 [3.53553391 2.12132034 0.70710678]]


In [85]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)
def extract_subpart(arr, shape, center, fill_value):
    # Convert inputs to NumPy arrays
    arr = np.array(arr)
    shape = np.array(shape)

    # Calculate the starting and ending indices for each dimension
    start = np.maximum(center - shape // 2, 0)
    end = np.minimum(start + shape, arr.shape)

    # Create an empty array with the desired shape and fill it with the fill value
    subpart = np.full(shape, fill_value)

    # Calculate the indices for the subpart within the full array
    subpart_start = start - (center - shape // 2)
    subpart_end = subpart_start + (end - start)

    # Copy the relevant portion from the full array to the subpart array
    subpart[subpart_start[0]:subpart_end[0], subpart_start[1]:subpart_end[1]] = arr[start[0]:end[0], start[1]:end[1]]

    return subpart

In [86]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4

R = sliding_window_view(Z, window_shape=(window_size,))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [87]:
#82. Compute a matrix rank

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank:", rank)

Rank: 2


In [88]:
#83. How to find the most frequent value in an array?

# Create an array
arr = np.array([1, 2, 3, 2, 4, 2, 1, 3, 2, 2])

# Count the occurrences of each value
counts = np.bincount(arr)

# Find the value with the maximum count
most_frequent_value = np.argmax(counts)

print("Most frequent value:", most_frequent_value)

Most frequent value: 2


In [89]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 
# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))

# Extract the contiguous 3x3 blocks
blocks = []
for i in range(8):  # Iterate over rows (0 to 7)
    for j in range(8):  # Iterate over columns (0 to 7)
        block = matrix[i:i+3, j:j+3]  # Extract the 3x3 block
        blocks.append(block)

# Display the extracted blocks
for block in blocks:
    print(block)
    print()

[[7 1 1]
 [8 2 5]
 [4 8 5]]

[[1 1 2]
 [2 5 8]
 [8 5 5]]

[[1 2 2]
 [5 8 4]
 [5 5 5]]

[[2 2 4]
 [8 4 9]
 [5 5 9]]

[[2 4 1]
 [4 9 4]
 [5 9 0]]

[[4 1 8]
 [9 4 2]
 [9 0 2]]

[[1 8 4]
 [4 2 7]
 [0 2 2]]

[[8 4 4]
 [2 7 3]
 [2 2 5]]

[[8 2 5]
 [4 8 5]
 [9 9 4]]

[[2 5 8]
 [8 5 5]
 [9 4 9]]

[[5 8 4]
 [5 5 5]
 [4 9 6]]

[[8 4 9]
 [5 5 9]
 [9 6 2]]

[[4 9 4]
 [5 9 0]
 [6 2 8]]

[[9 4 2]
 [9 0 2]
 [2 8 7]]

[[4 2 7]
 [0 2 2]
 [8 7 7]]

[[2 7 3]
 [2 2 5]
 [7 7 4]]

[[4 8 5]
 [9 9 4]
 [0 5 3]]

[[8 5 5]
 [9 4 9]
 [5 3 3]]

[[5 5 5]
 [4 9 6]
 [3 3 1]]

[[5 5 9]
 [9 6 2]
 [3 1 4]]

[[5 9 0]
 [6 2 8]
 [1 4 9]]

[[9 0 2]
 [2 8 7]
 [4 9 7]]

[[0 2 2]
 [8 7 7]
 [9 7 4]]

[[2 2 5]
 [7 7 4]
 [7 4 1]]

[[9 9 4]
 [0 5 3]
 [2 0 6]]

[[9 4 9]
 [5 3 3]
 [0 6 7]]

[[4 9 6]
 [3 3 1]
 [6 7 0]]

[[9 6 2]
 [3 1 4]
 [7 0 8]]

[[6 2 8]
 [1 4 9]
 [0 8 1]]

[[2 8 7]
 [4 9 7]
 [8 1 2]]

[[8 7 7]
 [9 7 4]
 [1 2 5]]

[[7 7 4]
 [7 4 1]
 [2 5 7]]

[[0 5 3]
 [2 0 6]
 [5 7 6]]

[[5 3 3]
 [0 6 7]
 [7 6 8]]

[[3 3 1]
 [6 7

In [91]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

class SymmetricArray(np.ndarray):
    def __getitem__(self, index):
        # Swap the indices for symmetry
        swapped_index = (index[1], index[0])
        return super().__getitem__(swapped_index)

# Create a symmetric 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sym_arr = arr.view(SymmetricArray)

# Test the symmetry property
print(sym_arr[0, 1])  # Output: 2
print(sym_arr[1, 0])  # Output: 2

4
2


In [92]:
#86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1).How to compute the sum of of the p matrix products at once? (result has shape (n,1))

# Set the number of matrices and their shape
p = 3
n = 4

# Create p matrices and p vectors
matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

# Compute the sum of p matrix products
result = np.sum([np.matmul(matrices[i], vectors[i]) for i in range(p)], axis=0)

print(result)

[[3.34386825]
 [3.70171959]
 [3.14564399]
 [3.63124351]]


In [93]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
# Create a 16x16 array
arr = np.arange(256).reshape(16, 16)

# Define the block size
block_size = 4

# Reshape the array to a block-shaped 4D array
block_arr = arr.reshape(4, 4, 4, 4)

# Compute the block-sum along the last two axes
block_sum = np.sum(block_arr, axis=(-2, -1))

print(block_sum)

[[ 120  376  632  888]
 [1144 1400 1656 1912]
 [2168 2424 2680 2936]
 [3192 3448 3704 3960]]


In [94]:
#88. How to implement the Game of Life using numpy arrays?
def game_of_life(grid, iterations):
    """
    Simulates the Game of Life for a given number of iterations.

    Args:
        grid (numpy.ndarray): The initial grid of cells.
        iterations (int): The number of iterations to simulate.

    Returns:
        numpy.ndarray: The final grid of cells after the specified number of iterations.
    """

    for _ in range(iterations):
        # Create a copy of the current grid for the next iteration
        next_grid = grid.copy()

        # Get the number of rows and columns in the grid
        rows, cols = grid.shape

        # Iterate over each cell in the grid
        for i in range(rows):
            for j in range(cols):
                # Count the number of live neighbors
                live_neighbors = np.sum(grid[max(i-1, 0):min(i+2, rows), max(j-1, 0):min(j+2, cols)]) - grid[i, j]

                # Apply the rules of the Game of Life
                if grid[i, j] == 1 and (live_neighbors < 2 or live_neighbors > 3):
                    next_grid[i, j] = 0
                elif grid[i, j] == 0 and live_neighbors == 3:
                    next_grid[i, j] = 1

        # Update the grid for the next iteration
        grid = next_grid

    return grid


In [95]:
#89. How to get the n largest values of an array 

# Create an array of random numbers
arr = np.random.randint(0, 100, 20)

# Number of largest values to retrieve
n = 5

# Get the n largest values
largest_values = -np.partition(-arr, n)[:n]

print(largest_values)

[95 97 85 79 76]


In [96]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

import itertools

# Define the vectors
vector1 = [1, 2]
vector2 = ['a', 'b', 'c']
vector3 = [True, False]

# Build the cartesian product
cartesian_product = list(itertools.product(vector1, vector2, vector3))

print(cartesian_product)

[(1, 'a', True), (1, 'a', False), (1, 'b', True), (1, 'b', False), (1, 'c', True), (1, 'c', False), (2, 'a', True), (2, 'a', False), (2, 'b', True), (2, 'b', False), (2, 'c', True), (2, 'c', False)]


In [97]:
#91. How to create a record array from a regular array?

# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 35)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Create a record array from the regular array
record_array = np.rec.array(regular_array)

print(record_array)
print(record_array.id)
print(record_array.name)
print(record_array.age)

[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]
[1 2 3]
['Alice' 'Bob' 'Charlie']
[25 30 35]


In [98]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

# Create a large vector Z
Z = np.random.rand(1000000)

# Compute Z to the power of 3 using NumPy's power function
result1 = np.power(Z, 3)

# Compute Z to the power of 3 using a loop
result3 = np.empty_like(Z)
for i in range(len(Z)):
    result3[i] = Z[i] ** 3

In [99]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
# Create arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 2, 9],
              [4, 6, 5],
              [7, 9, 8],
              [1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [4, 5]])

# Find rows of A that contain elements of each row of B
rows = np.where(np.logical_and.reduce(np.isin(A, B), axis=1))[0]

print(rows)

[]


In [100]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
# Create a 10x3 matrix
matrix = np.array([[1, 2, 3],
                   [2, 2, 2],
                   [4, 5, 6],
                   [7, 7, 7],
                   [1, 2, 9],
                   [4, 6, 5],
                   [7, 9, 9],
                   [1, 2, 3],
                   [4, 5, 6],
                   [1, 1, 1]])

# Extract rows with unequal values
unequal_rows = matrix[~np.all(matrix == matrix[0, :], axis=1)]

print(unequal_rows)

[[2 2 2]
 [4 5 6]
 [7 7 7]
 [1 2 9]
 [4 6 5]
 [7 9 9]
 [4 5 6]
 [1 1 1]]


In [101]:
#95. Convert a vector of ints into a matrix binary representation


# Create a vector of integers
vector = np.array([5, 3, 1, 7])

# Get the maximum value in the vector
max_value = np.max(vector)

# Determine the number of bits required to represent the maximum value
num_bits = int(np.ceil(np.log2(max_value + 1)))

# Convert the vector into a matrix binary representation
binary_matrix = np.unpackbits(vector.astype(np.uint8)[:, np.newaxis], axis=1)
binary_matrix = binary_matrix[:, -num_bits:]

print(binary_matrix)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]


In [102]:
#96. Given a two dimensional array, how to extract unique rows?
# Create a two-dimensional array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [103]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

# Define vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product of A and B
inner_product = np.einsum('i,i', A, B)
print("Inner product:", inner_product)

# Outer product of A and B
outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:")
print(outer_product)

# Element-wise sum of A and B
elementwise_sum = np.einsum('i,i->i', A, B)
print("Element-wise sum:", elementwise_sum)

# Element-wise multiplication of A and B
elementwise_multiply = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_multiply)

Inner product: 32
Outer product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Element-wise sum: [ 4 10 18]
Element-wise multiplication: [ 4 10 18]


In [104]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

# Define vectors X and Y
X = np.array([1, 2, 3, 4, 5])
Y = np.array([10, 20, 30, 40, 50])

# Number of samples
num_samples = 10

# Calculate the total length of the path
path_length = np.sum(np.sqrt(np.diff(X) ** 2 + np.diff(Y) ** 2))

# Calculate the step size
step_size = path_length / (num_samples - 1)

# Calculate the cumulative distances along the path
distances = np.cumsum(np.sqrt(np.diff(X) ** 2 + np.diff(Y) ** 2))

# Add zero at the beginning to represent the starting point
distances = np.insert(distances, 0, 0)

# Sample the path using equidistant samples
sampled_X = np.interp(np.linspace(0, path_length, num_samples), distances, X)
sampled_Y = np.interp(np.linspace(0, path_length, num_samples), distances, Y)

# Print the sampled path
for x, y in zip(sampled_X, sampled_Y):
    print(f"({x}, {y})")

(1.0, 10.0)
(1.4444444444444444, 14.444444444444445)
(1.8888888888888888, 18.88888888888889)
(2.3333333333333335, 23.333333333333336)
(2.7777777777777777, 27.77777777777778)
(3.2222222222222223, 32.22222222222222)
(3.666666666666667, 36.66666666666667)
(4.111111111111112, 41.111111111111114)
(4.555555555555555, 45.55555555555556)
(5.0, 50.0)


In [105]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

# Define the integer n and the 2D array X
n = 5
X = np.array([[1, 2, 2],
              [0, 5, 0],
              [2, 1, 2],
              [3, 0, 2]])

# Select rows that only contain integers and sum to n
selected_rows = X[(X.dtype == np.int64) & (np.sum(X, axis=1) == n)]

print(selected_rows)

[[1 2 2]
 [0 5 0]
 [2 1 2]
 [3 0 2]]


In [106]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

# Set the random seed for reproducibility
np.random.seed(42)

# Define the 1D array X
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Number of bootstrap samples
N = 1000

# Perform bootstrapping
bootstrap_means = []
for _ in range(N):
    # Resample with replacement
    bootstrap_sample = np.random.choice(X, size=len(X), replace=True)
    # Compute the mean of the bootstrap sample
    bootstrap_mean = np.mean(bootstrap_sample)
    bootstrap_means.append(bootstrap_mean)

# Compute the 95% confidence interval
confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])

print("Bootstrapped 95% Confidence Interval:", confidence_interval)

Bootstrapped 95% Confidence Interval: [3.7 7.3]
